export const TOGGLE_LEFT_NAV = 'TOGGLE_LEFT_NAV';
export const CLOSE_LEFT_NAV = 'CLOSE_LEFT_NAV';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const SET_SNACKBAR_MESSAGE = 'SET_SNACKBAR_MESSAGE';
export const SET_DIALOG_CONTENT = 'SET_DIALOG_CONTENT';
